package com.waiyan.myittar_oo_emr.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006191)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF007BB6)
val onPrimaryContainerLight = Color(0xFFFCFCFF)
val secondaryLight = Color(0xFF7F0C00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA51F0B)
val onSecondaryContainerLight = Color(0xFFFFB9AB)
val tertiaryLight = Color(0xFF723B3A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8E5251)
val onTertiaryContainerLight = Color(0xFFFFD6D4)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7F9FF)
val onBackgroundLight = Color(0xFF171C20)
val surfaceLight = Color(0xFFFCF8F8)
val onSurfaceLight = Color(0xFF1C1B1B)
val surfaceVariantLight = Color(0xFFDAE3EE)
val onSurfaceVariantLight = Color(0xFF3F4850)
val outlineLight = Color(0xFF6F7881)
val outlineVariantLight = Color(0xFFBEC7D2)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF3F0EF)
val inversePrimaryLight = Color(0xFF8FCDFF)
val surfaceDimLight = Color(0xFFDCD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

val primaryDark = Color(0xFF8FCDFF)
val onPrimaryDark = Color(0xFF003450)
val primaryContainerDark = Color(0xFF1899DE)
val onPrimaryContainerDark = Color(0xFF002940)
val secondaryDark = Color(0xFFFFB4A6)
val onSecondaryDark = Color(0xFF660800)
val secondaryContainerDark = Color(0xFFA51F0B)
val onSecondaryContainerDark = Color(0xFFFFB9AB)
val tertiaryDark = Color(0xFFFFB3B1)
val onTertiaryDark = Color(0xFF522121)
val tertiaryContainerDark = Color(0xFF8E5251)
val onTertiaryContainerDark = Color(0xFFFFD6D4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1418)
val onBackgroundDark = Color(0xFFDFE3E9)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF3F4850)
val onSurfaceVariantDark = Color(0xFFBEC7D2)
val outlineDark = Color(0xFF89929B)
val outlineVariantDark = Color(0xFF3F4850)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF006495)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353534)




